### ISSUE TITLE
Napaka

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/Iskalnik-pesmi#2]
Ko zaženemo kodo v datoteki povezava.R, nam da naslednjo napako:
Error: package or namespace load failed for ‘dbplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘DBI’ 0.6-1 is already loaded, but >= 0.7 is required
In addition: Warning message:
package ‘dbplyr’ was built under R version 3.4.4

**Comment by jaanos** [comment]
Bomo jutri poskusili pogledati, kaj je narobe.
