### ISSUE TITLE
napaka v brisanju vrstic

### ISSUE THREAD

**Issue by NabergojV** [marinasirk/Iskalnik-pesmi#4]
```# tabela nosilec
nosi <- tidy_tabela[,c(1,3)]

n <- c()
for(n in nosi$"album name"){
  if(!(n %in% nosi)){
    nosi<- nosi[-c(n)]
  }
}
nosilec <- nosi```
Kako bi iz tabele izbrisale vrstico, ki se ponovi večkrat? V tabeli je prvi stolpec izvajalec, drugi album, ki se ponovi večkrat, zato bi želele izbrisati te vrstice na podlagi albumov.

**Comment by MarvinHerzog** [comment]
Ali ukaz `unique(nosi)` naredi to kar želite? Potem dobite tabelo take oblike:

|                                      |  artist  |                                 album name|
| --- | --- | --- |
|4              |                   Ace of Base                  |               Happy Nation|
|16         |                       Ace of Base                  |                 The Bridge|
|32                   |             Ace of Base                       |               Flowers|
|48                   |             Ace of Base                       |               Da Capo|
|92                      |         Alan Jackson              |         Here In the Real World|
|100                    |          Alan Jackson              |         Don't Rock the Jukebox|

**Comment by marinasirk** [comment]
Dela, hvala.
