### ISSUE TITLE
problem integer

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/Iskalnik-pesmi#5]
Ko želimo vstaviti podatke v tabelo ```izvaja```, nam javi, da ```izvajalec(id)``` ni integer, vendar smo ga definirale kot takega.
``` Error in postgresqlgetResult(new.con) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid input syntax for integer: "Ace of Base"
CONTEXT:  COPY izvaja, line 1, column izvajalec: "Ace of Base"
) ```

**Comment by MarvinHerzog** [comment]
V vrstici ` dbWriteTable(conn, name="izvaja", izvaja, append=T, row.names=FALSE)`  poskušate v SQL tabelo  **`izvaja`** vstaviti _data.frame_ `izvaja` iz `uvoz.R`. Vaša SQL tabela ima stolpce definirane tako:

|Column| Type|
|--|--|
| id | integer | 
| izvajalec | integer | NOT NULL |  
| pesem | integer |

Po drugi strani, _data.frame_ `izvaja` iz uvoz.R zgleda tako:

|   izvajalec    |          pesem|
|--|--|
 |Ace of Base |  Don't Turn Around |
|Ace of Base|    Young and Proud|
 |Ace of Base|           The Sign|
| Ace of Base|   Living In Danger|
| Ace of Base |Voulez-vous Danser|

Kot vidite, v zadnji tabeli nimate stolpca  `ID`. Predlagam, da tega kar odstranite iz vaše SQL tabele, saj je tabela **`izvaja`** zgolj vezna tabela med ID-ji SQL tabel **`izvajalec`** in **`pesem`** in tako ne potrebuje svojih ID-jev. Hkrati sta v _data.frame_ `izvaja` stolpca vrste _factor_ oz. _string_. V teh dveh stolpcih boste potrebovale ID-je (in ne imena) ustreznih izvajalcev ter pesmi. Te lahko dobite tako, da v R uporabite ukaz `merge`, da združite tabele `pesem` - `izvaja` - `izvajalec` in iz njih poberete potrebne ID-je, te pa nato vstavite v SQL tabelo **`izvaja`**.

Primer:
```
merge(x = izvaja, y = pesem, by.x = "pesem", by.y = "naslov")
```

**Comment by marinasirk** [comment]
Pri ukazu ```merge``` pride pa do problema, ker imajo nekatere pesmi enak naslov. Zaradi tega se nam zgodi, da ima ```ID``` ene pesmi lahko dva izvajalca. Kako bi to lahko popravili?

**Comment by marinasirk** [comment]
Ni treba več, smo že popravile.

**Comment by marinasirk** [comment]
Še en problem se je pojavil pri veznih tabelah, in sicer pri tabeli ```nosi``` ter ```nahaja```. V mapi ```uvoz.R``` sta definirani in so indeksi pravilni, vendar v mapi ```povezava.R``` javi spodnjo napako:
```Error in postgresqlgetResult(new.con) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  insert or update on table "nosi" violates foreign key constraint "nosi_album_id_fkey"
DETAIL:  Key (album_id)=(397) is not present in table "album".
)
```

**Comment by MarvinHerzog** [comment]
Na vaši bazi, v tabeli `album`, imate albume samo do id _395_, kličete pa id z vrednostjo _397_ . Bom jutri preveril, če se kaj zalomi pri tem ko z R-om uvozite podatke v bazo.

**Comment by MarvinHerzog** [comment]
Težava je v tem, da ste dvakrat (različno) definirale tabelo z albumi. Prvič tukaj: 

```
# tabela album

naslov_albuma <-c()
for(album in tidy_tabela$`album name`){
  if(!(album %in% naslov_albuma)){
    naslov_albuma=c(naslov_albuma, album)
  }
}
album_id <- c(1:length(naslov_albuma))
album=data.frame(id=album_id, naslov=naslov_albuma)
```

drugič pa tu:

```
# tabela nahaja
album1 <- tidy_tabela[,c(3,4)]
album1 <- unique(album1)
album1_id <- c(1:length(album1$year))
album1 <- data.frame(album1_id, album1)
colnames(album1) <- c("album_id", "album", "leto")
```

Te tabeli sta različnih velikosti.
```
> dim(album)
[1] 395   2
> dim(album1)
[1] 400   2
```
To je zato, ker se v vaših podatkih zgodi, da imata dva albuma enako ime, vendar sta izdana v različnih letih. 
```
>album1$`album name`[duplicated( album1$`album name`)]
     [,1]                             
[1,] "Amarantine"                     
[2,] "Laura Pausini (Italian Version)"
[3,] "Pure Pleasure"                  
[4,] "Thalia"                         
[5,] "La Banda Timbiriche"     
```
Primer za album _Amarantine_:
```
> tidy_tabela[tidy_tabela$`album name`=="Amarantine",]
2412   Enya                     Drifting Amarantine 2005 New Age       04:11
2413   Enya                     Drifting Amarantine 2005 New Age       03:38
2414   Enya Water Shows the Hidden Heart Amarantine 2005 New Age       04:41
2415   Enya                 Orinoco Flow Amarantine 2007 New Age       03:44
2416   Enya                    May It Be Amarantine 2007 New Age       03:32
2417   Enya                    Only Time Amarantine 2007 New Age       03:41
```

Drugo definicijo uporabljate, da ustvarite tabeli `nosi` in `nahaja`, prvo pa pač kot tabelo `album`.
```
nahaja2 <- merge(nahaja1, album1, by = c("album", "leto"))
nosi1 <- merge(nosi1, album1, by = c("album", "leto"))
```
To vam močno odsvetujem, saj se bodo tako imena albumov ter ID-ji samo pomešali. Najbolje, da izberete eno definicijo tabele `album` (same se odločite, če boste dovolile albume z enakimi imeni/različnimi letnicami ali ne). V tej definirajte ID-je, te pa potem uporabljajte za ostale tabele preko `merge` ali česa podobnega.

Mimogrede, svetujem vam še, da v 

```
uvozi<-function(){
  return(read.csv2(file="Music-Database.csv",
                   skip=11,
                   header=FALSE,
                   fileEncoding = "UTF-8",
                   na=c("","??")))
}
```

namesto `fileEncoding` uporabljate `encoding`. Sicer ne vem kako je s tem na drugih računalnikih, vendar če nisem spremenil te vrstice, mi R ni želel prebrat vseh vrstic in je vrnil warning:

```
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  invalid input found on input connection 'Music-Database.csv'
```

Vidim tudi, da imate v kodi ukaz `write.csv(tidy_tabela, "tabela.csv")`, čeprav te tabele ne uporabljate.

**Comment by MarvinHerzog** [comment]
V R-ovi tabeli `izvaja` imate vrstni red stolpcev obraten, kot je v SQL tabeli `izvaja`.

**Comment by NabergojV** [comment]
Smo popravile! Hvala!
Sedaj nam pri zagonu shiny-ja vrne sledečo napako:
```Listening on http://127.0.0.1:7029
Warning: package ‘dplyr’ was built under R version 3.4.4

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Warning: Error in $.shinyoutput: Reading objects from shinyoutput object not allowed.
  50: stop
  49: $.shinyoutput
  47: server [C:\Users\david\Documents\Iskalnik-pesmi\Shiny/server.R#30]
Error in `$.shinyoutput`(output, tabelaleta) : 
  Reading objects from shinyoutput object not allowed.
Warning: Error in as.vector: cannot coerce type 'closure' to vector of type 'character'
  95: as.character.default
  93: paste
  92: renderText [C:\Users\david\Documents\Iskalnik-pesmi\Shiny/server.R#14]
  91: func
  78: origRenderFunc
  77: output$leto1
   1: runApp
Warning: Error in as.vector: cannot coerce type 'closure' to vector of type 'character'
  95: as.character.default
  93: paste
  92: renderText [C:\Users\david\Documents\Iskalnik-pesmi\Shiny/server.R#15]
  91: func
  78: origRenderFunc
  77: output$dolzina2
   1: runApp
Warning: Error in match: 'match' requires vector arguments
  103: %in%
  100: function_list[[k]]
   98: freduce
   97: _fseq
   96: eval
   95: eval
   93: %>%
   92: renderDataTable [C:\Users\david\Documents\Iskalnik-pesmi\Shiny/server.R#22]
   91: func
   78: origRenderFunc
   77: output$tabelapesmi
    1: runApp´´´´

**Comment by MarvinHerzog** [comment]
Glavni problem je v tem, da je potrebno podatke iz `reactive` objekta dobiti tako, da na konec dodate še `()`, kot pri funkcijah. Npr.:

```
  leto<-reactive({tbl(conn,"pesem")%>%filter(naslov==input$pesem1)%>%select(leto)%>% pull()})
  leto()
```
Ravno tako lahko v reactive objektih definirate več spremenljivk. Najbolje, da kar združite tiste, ki spadajo skupaj. Na koncu stavkov sem uporabil `pull()`, da sem dobil vrednosti elementov.

```
    dolzina<-reactive({tbl(conn,"pesem")%>%filter(naslov==input$pesem1)%>%select(dolzina)%>% pull()})
    leto<-reactive({tbl(conn,"pesem")%>%filter(naslov==input$pesem1)%>%select(leto)%>% pull()})
    izvajalec<-reactive({
      indeks<-tbl(conn,"pesem")%>%filter(naslov==input$pesem1)%>%select(id) %>% pull()
      izvajalec_id1<-tbl(conn,"izvaja")%>%filter(pesem_id==indeks)%>%select(izvajalec_id)%>% pull()
      tbl(conn,"izvajalec")%>%filter(id==izvajalec_id1)%>%select(ime)%>% pull()
    })
  
  output$pesem2<-renderText({paste("Izvajalec",izvajalec() )})
  output$leto1<-renderText({c(paste("Leto: ",leto()  ))})
  output$dolzina2<-renderText({c(paste("Dolzina: ",dolzina()  ))})
  ```
Zraven tega sem namesto `renderDataTable` uporabil `renderTable`. V render objektih ne rabite posebej definirat reaktivnih objektov, ker so že sami po sebi reaktivni. V definiciji `pesmice` namesto `subset` uporabite `filter`.
```
  output$tabelapesmi<-renderTable({
    indeks2<-tbl(conn,"album")%>%filter(naslov==input$album)%>%select(id)%>% pull()
    pesmiceid<-tbl(conn,"nahaja")%>%filter(album_id==indeks2)%>%select(pesem_id)%>% pull()
    pesmice<-tbl(conn,"pesem") %>% filter(id %in%pesmiceid)
    pesmice    
  })

```
Svetujem vam še, da preko `if` stavkov ali z uporabo `tryCatch` obdelate situacijo, ko vam iskanje albuma ali pesmi ne vrne nobenih rezultatov (sicer se prikazujejo napake).

**Comment by marinasirk** [comment]
Odlično, hvala.
Kako pa bi naredile to, da bi na primer najprej na prvi strani imeli možnost izbire načina iskanja (iskanje po naslovu pesmi, iskanje po albumu, iskanje po zvrsti in iskanje po letu) in bi se potem odprla nova stran, kjer bi iskali po željeni izbiri?

**Comment by marinasirk** [comment]
In še to: v datoteki ```server.R``` nam javlja dve napaki.
Prva je pri iskanju po izvajalcu:
``` 
Warning: Error in .subset2: subscript out of bounds
```
druga pa pri iskanju po letu:
```
Warning: Error in postgresqlExecStatement: RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near ")"
LINE 4: WHERE ("leto" > )) "dgpddgnkcj"
                        ^
```

**Comment by MarvinHerzog** [comment]
V `server.R` se iskanju po letu sklicujete na `min` in `max`, ki nista input spremenljivki. Ti dve vrednosti vam zgolj določata razpon sliderja, ne pa trenutno vrednost. Ta se skriva pod `input$leto`. Sklepam, da želite filtrirati po letih znotraj nekega intervala. [To lahko dosežete tako](http://shiny.rstudio.com/gallery/slider-bar-and-slider-range.html), da v `ui.R` `value` definirate kot seznam dveh vrednosti. Potem se pojavita dva krogca, ki ju lahko lahko pomikate, da določite interval.

```
      sliderInput("leta",
                  "Leto skladbe:",
                  min = 1970,
                  max = 2015,
                  value = c(1980,2000))
    ),
```

V `server.R` nato kličete prvi oz. drugi element tega seznama, ki sta določena s trenutnim položajem krogcev.

```
   output$tabelaleta <- renderTable({
    l <- tbl.pesem %>% filter(leto >= input$leta[1]) %>% filter(leto <= input$leta[2]) %>% arrange(leto) %>% data.frame()
    l
   })

})
```
Kar se tiče `Warning: Error in .subset2: subscript out of bounds`. Ta napaka se vam pojavlja, ko vaš izbor ne vrne nobenih rezultatov. Kot sem že omenil v prejšnjem issue, dodajte pogoj, ki preverja ali je tabela (ki je rezultat filtriranja) prazna. V tem primeru vrnite kak string "Ni rezultatov", ali kaj podobnega.
Trenutno se ta napaka pojavlja tudi zato, ker so tabele na vaši SQL bazi prazne. 

Glede vašega prvega vprašanja vidim dve rešitvi. Prva je uporaba `tabsetPanel`:

https://shiny.rstudio.com/articles/tabsets.html
https://shiny.rstudio.com/reference/shiny/1.1.0/tabsetPanel.html
https://github.com/MancaStrgar/Brskalnik-po-spletnih-trgovinah/blob/master/shiny/ui.R

S tem lahko vsak način iskanja pospravite v ločen zavihek.

Druga rešitev bi bila, da imate vse tipe iskanja kar na eni strani, podobno kot jih imate sedaj. Vaše iskanje bi nato prilagodili tako, da lahko uporabnik išče pesmi po enem ali več kriterijih hkrati. To bi storili na tak način, da imate privzeto vrednost vsakega iskalnega polja prazna (namesto npr. _Happy Nation_). V primeru, ko je iskalno polje prazno, se tisti filter ignorira. Kot rezultat bi vrnili samo eno tabelo, ki hkrati upošteva vse neprazne filtre.

Primer: [Amazon](https://www.amazon.com/Advanced-Search-Books/b?ie=UTF8&node=241582011)

**Comment by tajadebeljak** [comment]
Hvala, smo rešile z uporabo tabsetPanel.

Sedaj nas zanima zakaj nam ne vpiše podatkov v sql tabele, vrne nam namreč napako:

```  Error in dbWriteTable(conn, name = "izvajalec", izvajalec, append = T,  : 
  object 'izvajalec' not found ```

**Comment by MarvinHerzog** [comment]
Ker ste delale na Shiny aplikaciji, ugibam, da ima R trenutno kot delovno mapo nastavljeno /Iskalnik-pesmi/Shiny/. V tem primeru `source("uvoz.r", encoding="UTF-8")` vrne napako `cannot open file 'uvoz.r': No such file or directory`, torej se tabela `izvajalec` iz uvoza sploh ne naloži v delovno okolje. To lahko rešite tako, da uporabite ukaz `setwd("..")`, ki vas postavi eno mapo višje. Lahko pa tudi zaprete RStudio in ga zaženete tako, da direktno odprete datoteko `povezava.R`.

**Comment by NabergojV** [comment]
Pri uporabi try catch ne popravi primera, ko je pesem napačne, vrne še vedno ``` Error: subscript out of bounds.
```
To pa tudi vrne če je polje prazno. Kako to popravimo?

**Comment by NabergojV** [comment]
V shinyu nam v vsakem zavihku doda tudi id, ta stolpec smo poskusile izbrisati pri ```seznam_pesmi``` ,(iskanje po izvajalcu v ```server.R``` ) vendar vrne napako, da je napačnih dimenzij.

**Comment by MarvinHerzog** [comment]
Hmm, vidim da ima `tryCatch` težave s reactive objekti. Ena (nekoliko groba) rešitev je taka:

```
  izvajalec <- reactive({
    indeks1=tbl.pesem %>% filter(naslov==input$pesem1)
    if(count(indeks1)%>%pull()==0){
      return("Pesmi ni v bazi")
    } else{
      indeks= indeks1%>% select(id) %>% pull()
      izvajalec_id1 <- tbl.izvaja %>% filter(pesem_id==indeks) %>% select(izvajalec_id) %>% pull()
      izv<-tbl.izvajalec %>% filter(id==izvajalec_id1) %>% select(ime) %>% pull()
      paste("Izvajalec: ", izv )
    }
  })
  
  dolzina <- reactive({
    dolz=tbl.pesem %>% filter(naslov==input$pesem1)
    if(count(dolz)%>%pull()==0){
      return("")
    } else{
      dolz2=dolz %>% select(dolzina) %>% pull()
      paste("Dolžina: ", dolz2 )
    }
    })
```
Torej da preko _if_ stavkov obdelate situacijo, ko je število vrstic 0. V tem primeru se samo pri izvajalcu izpiše, da pesmi ni v bazi. V ostalih reactive objektih pa lahko vrnete prazen string. Nato podate output kot

```
  output$pesem2 <- renderText(izvajalec())
  output$dolzina1 <- renderText(dolzina())
```

Zadevo podobno kot pri _dolžini_ ponovite za vse ostale outpute. Lahko bi se izognili precej podvajanju kode tako, da bi vse zapakirali v en reactive objekt, nato pa rezultat podali kot seznam. V primeru prazne tabele _indeks_ bi pa recimo vrnili seznam `c("Pesmi ni v bazi", "", "", "", "")`.

Glede drugega vprašanja, stolpca _ID_ se znebite tako, da na koncu dodate še `select` po željenih stolpcih, torej

```
  output$seznam_pesmi <- renderTable({
    indeks <- tbl.izvajalec %>% filter(ime==input$izvajalec) %>% select(id) %>% pull()
    pesmiid <- tbl.izvaja %>% filter(izvajalec_id==indeks) %>% select(pesem_id) %>% pull()
    pesmic <- tbl.pesem %>% filter(id %in% pesmiid) %>% select(c(naslov,leto,dolzina))
    pesmic
  })
```
Mimogrede, v tem bloku ne potrebujete `tbl(conn, "izvaja")`, ker ga že imate definirane na začetku kot `tbl.izvaja`.

**Comment by NabergojV** [comment]
Hvala! Smo popravile. Pri izvajalcu smo poskusile uvesti if stavke, vendar ne vemo, če smo naredila na pravilen način, saj nam sedaj vrže napako, če polje vsebuje izvajalca iz databaze, če pa izvajalci ni, vrne pravilno opozorilo za uporabnika. Zanima nas še ena stvar in sicer, na kakšen način bi uvedle da pri vpisovanju besedila v ```input``` ni važna velika začetnica.

**Comment by MarvinHerzog** [comment]
V reactive objektih `izvajalec` in `dolzina` ne dodajajte `renderText` outputov. `renderText(izvajalec())` že prejme rezultat, ki ga vrne reactive blok `izvajalec` - to je `return("Pesmi ni v bazi")` ob prazni tabeli oziroma (return) `paste("Izvajalec: ", izv )` ko najde rezultat. Samo nadomestite objekte z kodo, ki sem jo dodal v prejšnjem komentarju pa bi moralo delati. Potem pa morate samo še narediti narediti kopije za _album, leto_ in _zvrst_. Če še vedno ne bo šlo, mi sporočite in bom naredil merge request.

Glede velikih začetnic lahko spremenite `filter(naslov==input$pesem1)` v `filter(tolower(naslov)==tolower(input$pesem1))`. Enako pri ostalih filtrih.

**Comment by NabergojV** [comment]
Če smo samo nadomestile kodo, je pri iskanju po pesmi (v primeru da pesmi ni bilo v bazi) vrnilo prvo vrstico: ```"Pesmi ni v bazi"``` in pod tem še vedno 4 Errorje: ```Subscript out of bounds.``` Kot je koda sedaj napisana, pa vrne samo ```Pesmi ni v bazi```.
V primeru ko smo po istem postopku kot je ```dolzina``` skušale preurediti iskanje po izvajalcu nam vrne to napako:
```
data
--
list(con = <S4 object of class "PostgreSQLConnection">, disco = <environment>)
list(name = "filter", x = list(x = "pesem", vars = c("id", "naslov", "leto", "dolzina")), dots = list(~id %in% 1:57), args = list())
```
Torej ne vemo kje smo tu zgrešile, pri preurejanju preostalih po zgledu ```dolzine```

**Comment by MarvinHerzog** [comment]
Odprl sem pull request tukaj:
https://github.com/marinasirk/Iskalnik-pesmi/pull/6
Prosil bi vas, da sprejmete združitev.

Po zgledu `izvajalec`/`dolzina` sem dodal še ostale reactive bloke, tako da bi zdaj iskanje po pesmih moralo delovati. Mimogrede sem še spremenil del pri iskanju po izvajalcu, saj je vračal napake. Pri tem sem odstranil reactive objekt `sez_pesmi` in vso njegovo vsebino dodal v `renderTable` `output$seznam_pesmi`. 

V `ui.R` sem zaenkrat zakomentiral `vse_pesmi <- pesmi$naslov` in pripadajoč `selectInput`, saj objekta `pesmi` nimate definiranega ne v `server.R` ne v `ui.R` (ste ga morda imele naloženega v _Global Environment_?). Tako sem začasno odkomentiral in uporabil `textInput` za izbor pesmi, ki ste ga uporabljale prej. Če zares želite imeti dropdown seznam z vsemi pesmimi, bo najbolje, da v `server.R` uporabite `renderUI`, [primer](https://stackoverflow.com/questions/21465411/r-shiny-passing-reactive-to-selectinput-choices).

**Comment by NabergojV** [comment]
Najlepša hvala za vso pomoč!
